# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      fail:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Should I fail?'
        # Default value if no value is explicitly provided
        default: "yes"
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  failOrNot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Fail
      if: ${{ github.event.inputs.fail == 'yes' }}
      run: exit 1
  
    - name: Pass
      if: ${{ github.event.inputs.fail == 'no' }}
      run: exit 0
    
    - name: On failure
      if: ${{ failure() }}
      run: echo "${{ github.workflow }} failed! See https://github.com/lukehedger/actions-failure/actions/runs/${{ github.run_id }}"
